wrote a markdown for the 2nd page
Vanderwise/device pull request #3
Opened 2022-10-25 14:46 UTC by Vanderwise

2022-10-26 14:10 UTC, ratetenyov commented on device-catalog.html
> +                <a class="nav_link" href=".//index.html"><img src=".//img/logo-black.png" alt="Logo device"></a>
this logo can be just a text Device inside of anchor tag), but your version is not a mistake

2022-10-26 14:12 UTC, ratetenyov commented on device-catalog.html
> +                    <!-- Тут должна быть какая-то переменная для username -->
what kind of variable, here should be Валентин Петухов literally)

2022-10-26 14:13 UTC, ratetenyov commented on device-catalog.html
> +                    <li><a href="#">Выйти</a></li>
I think it should be combined with Valenting Petukhov name

2022-10-26 14:15 UTC, ratetenyov commented on device-catalog.html
> +                    <li><a href="#">Корзина</a></li>
by the way, .svg files can be a source of `img` tags

2022-10-26 14:16 UTC, ratetenyov commented on device-catalog.html
> +                        <div class="catalog_div">
no need in this wrapper

2022-10-26 14:17 UTC, ratetenyov commented on device-catalog.html
> +                        <img src=".//img/plus.svg">
it can be a pseudo element
always remember that images block page's rendering, the less images,the faster your site

2022-10-26 14:18 UTC, ratetenyov commented on device-catalog.html
> +            <h2>Каталог товаров. Моноподы для селфи</h2>
I would use h1 here.

2022-10-26 14:22 UTC, ratetenyov commented on device-catalog.html
> +                <li><img src="./img/nav-arrow.svg" alt="стрелка"></li>
it's a pseudo element

2022-10-26 14:22 UTC, ratetenyov commented on device-catalog.html
> +                <li><img src="./img/nav-arrow.svg" alt="стрелка"></li>
same

2022-10-26 14:23 UTC, ratetenyov commented on device-catalog.html
> +            <div class="catalog_menu">
this will be a dropdown menu, and it relates to Каталог товаров in header

2022-10-26 14:24 UTC, ratetenyov commented on device-catalog.html
> +                <p>Сортировка:</p>
h2 maybe?

2022-10-26 14:52 UTC, ratetenyov commented on device-catalog.html
> +                    <li><button type="button">По цене</button></li>
these are links. clicking on them user sees change of the url. and this sortment can be done by change of the url without click on this link

2022-10-26 14:53 UTC, ratetenyov commented on device-catalog.html
> +                <button type="button"><img src="./img/icon-up-dir.svg" alt="вверх"></button>
links as well

2022-10-26 14:55 UTC, ratetenyov commented on device-catalog.html
> +                        <p>500 руб.</p>
please add parts of the card, that appears on hover (see styleguide)

2022-10-26 15:01 UTC, ratetenyov commented on device-catalog.html
> +                        <img src=".//img/item-1.jpg" alt="Любительская селфи-палка" width="360" height="380">
are sure such patht `.//img...` will work?

2022-10-26 15:03 UTC, ratetenyov commented on device-catalog.html
> +                <button type="button">назад</button>
link, not button. remember: if url changes, you need a link)

2022-10-26 15:03 UTC, ratetenyov commented on device-catalog.html
> +                <button type="button">вперед</button>
link

2022-10-26 15:03 UTC, ratetenyov commented on device-catalog.html
> +                    <button type="button">1</button>
links

2022-10-26 15:04 UTC, ratetenyov commented on device-catalog.html
> +            <aside>
good choice

2022-10-26 15:05 UTC, ratetenyov commented on device-catalog.html
> +                <div>
all filter inputs are inside of form tag

2022-10-26 15:06 UTC, ratetenyov commented on device-catalog.html
> +                    <!-- <input type="range" min="0" max="9000" step="1000" value="100"> -->
please add input type range

2022-10-26 15:09 UTC, ratetenyov commented on device-catalog.html
> +                        <li><input type="checkbox">Черный</li>
where is label? read one more time about inputs and their labels

2022-10-26 15:10 UTC, ratetenyov commented on device-catalog.html
> +                    <p>Цвет</p>
maybe h tag, what do you think?

2022-10-26 15:11 UTC, ratetenyov commented on device-catalog.html
> +                    <p>Bluetooth</p>
also h? but it's debatable

2022-10-26 15:11 UTC, ratetenyov commented on device-catalog.html
> +                    <p><input type="radio">Нет</p>
same story with input/label pair

2022-10-26 15:14 UTC, ratetenyov commented on device-catalog.html
> +                </div>
I didn't notice `Показать` button

2022-10-26 15:15 UTC, ratetenyov commented on device-catalog.html
> +                <img src=".//img/lable-new.png" alt="new">
what this image is for?

2022-10-26 15:17 UTC, ratetenyov commented on device-catalog.html
> +</html>
add end line please

2022-10-30 17:56 UTC, ratetenyov commented on css/style.css
> +        url(.//fonts/gilroylight.woff2) format('woff2');
where are font-weight and font-style properties?

2022-10-31 05:35 UTC, ratetenyov requested changes

2022-10-31 05:35 UTC, ratetenyov commented on css/style.css
> +        url(.//fonts/opensans.woff2) format('woff2');
same.

2022-10-31 05:35 UTC, ratetenyov commented on css/style.css
> +    font-weight: 400;
no need, since you specified it in @font-face

2022-10-31 05:35 UTC, ratetenyov commented on css/style.css
> +    list-style: none;
as well, reset paddings and margins to zero. it's even better to do it in normalize file

2022-10-31 05:35 UTC, ratetenyov commented on css/style.css
> +.search::before {
you forgot about `position` property for pseudo element

2022-10-31 05:35 UTC, ratetenyov commented on css/style.css
> +    padding: 0 13px 0 0;
`position`

2022-10-31 05:35 UTC, ratetenyov commented on css/style.css
> +.button-compare::before {
`position`, relates to all pseudo elements in your code

2022-10-31 05:35 UTC, ratetenyov commented on css/style.css
> +    padding: 0 11px 0 0;
maybe `padding-right: 11px` will be enough?

2022-10-31 05:35 UTC, ratetenyov commented on css/style.css
> +    font-size: 18px;
I guess this font-size relates to children items of nav.. it's better to specify font-size in place where you user font-family property

2022-10-31 05:35 UTC, ratetenyov commented on css/style.css
> +    display: flex;
position?

2022-10-31 05:35 UTC, ratetenyov commented on css/style.css
> +    height: 40px;
this is strange that content-link changes it's height on hover and focus

2022-10-31 05:35 UTC, ratetenyov commented on css/style.css
> +    display: flex;
is on propery is the same as without it, we can just skip it
add only that property, that changes on hover

2022-10-31 05:35 UTC, ratetenyov commented on css/style.css
> +.content-link:focus {
same as in hover

2022-10-31 05:35 UTC, ratetenyov commented on css/style.css
> +    align-items: center;
always try to group properties, all flex properties, all font, all background, etc. 
in this case, plese put together display: flex, aligh-items, justify-content

2022-10-31 05:35 UTC, ratetenyov commented on css/style.css
> +    padding: 0 0 0 24px;
padding-left. if labels have inbuilt padding, reset them, where you reset default styles for other elements

2022-10-31 05:35 UTC, ratetenyov commented on css/style.css
> +}
no empty line

2022-10-31 05:35 UTC, ratetenyov commented on registration.html
> +            <a class="nav_link" href=".//index.html"><img src=".//img/logo-black.png" alt="Логотип надпись device черным цветом"></a>
does such path `.//img/logo-black.png` work? I would recommend `img/logo-black.png`

2022-10-31 05:35 UTC, ratetenyov commented on registration.html
> +                    <input id="password" type="password" name="password"placeholder=Пароль>
missing space before `placeholder` ))

2022-10-31 05:35 UTC, ratetenyov commented on registration.html
> +</html>
empty line

2022-10-31 05:35 UTC, ratetenyov commented on css/normalize.css
> +}
I would add resetting of margins and paddings of h1, h2, h3, h4, h5, h6, p tags

 h1,h2,h3,h4,h5,h6,p {
  margin: 0,
  padding: 0,
}

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                <a class="nav_link" href=".//index.html"><img src=".//img/logo-black.png" alt="Logo device"></a>
I followed the section 3.10. Логотип — это ссылка на главную страницу

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                    <!-- Тут должна быть какая-то переменная для username -->
I meant it for real site :) Wrote Валентин Петухов

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                    <li><a href="#">Выйти</a></li>
OK

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                    <li><a href="#">Корзина</a></li>
Ok. Added img tag fot links

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                        <div class="catalog_div">
removed

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                        <img src=".//img/plus.svg">
the topic of pseudo-element is unknown to me. And now it's real mess in my head of how to present img (svg, png) on the page.

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +            <h2>Каталог товаров. Моноподы для селфи</h2>
have no idea why I used h2. Changed to h1

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +            <div class="catalog_menu">
moved to header

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                <li><img src="./img/nav-arrow.svg" alt="стрелка"></li>
:)

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                <li><img src="./img/nav-arrow.svg" alt="стрелка"></li>
ok

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                <p>Сортировка:</p>
yes

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                    <li><button type="button">По цене</button></li>
OK, changed to the link

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                <button type="button"><img src="./img/icon-up-dir.svg" alt="вверх"></button>
and is img as pseudo-element?

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                        <img src=".//img/item-1.jpg" alt="Любительская селфи-палка" width="360" height="380">
Yes, it shows the img. Is something wring with .//?

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                        <p>500 руб.</p>
add 2 buttons for each item. Not sure, that this way is correct.

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                <button type="button">назад</button>
ok

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                    <button type="button">1</button>
Ok

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                <button type="button">вперед</button>
OK

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                <div>
wrote

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +            <aside>
:)

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                    <!-- <input type="range" min="0" max="9000" step="1000" value="100"> -->
add but it's not correct

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                    <p>Цвет</p>
rewrote as it was shown in lecture

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                        <li><input type="checkbox">Черный</li>
rewrote as it was shown in lecture

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                    <p>Bluetooth</p>
rewrote as it was shown in lecture

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                    <p><input type="radio">Нет</p>
:)

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                </div>
Done

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +                <img src=".//img/lable-new.png" alt="new">
This is logo DEVICE img

2022-10-31 11:10 UTC, Vanderwise commented on device-catalog.html
> +</html>
what do you mean?

2022-10-31 11:10 UTC, Vanderwise commented on css/style.css
> +        url(.//fonts/gilroylight.woff2) format('woff2');
Done

2022-10-31 11:10 UTC, Vanderwise commented on css/style.css
> +        url(.//fonts/opensans.woff2) format('woff2');
Done

2022-10-31 11:10 UTC, Vanderwise commented on css/style.css
> +    font-weight: 400;
Ok

2022-10-31 11:10 UTC, Vanderwise commented on css/style.css
> +    padding: 0 11px 0 0;
For now I don't see a difference between these two declarations.

2022-10-31 11:10 UTC, Vanderwise commented on css/style.css
> +    list-style: none;
rewatch lectures and according to it to write
ul {list-style: none}; - is not goos idea, but i don't understand why is not good in this project. 
[html-lecture page 56.pdf](https://github.com/Vanderwise/device/files/9898900/html-lecture.page.56.pdf)

2022-10-31 11:10 UTC, Vanderwise commented on css/style.css
> +    font-size: 18px;
moved this declaration from nav to nav-list li because it relate to li, but font-family inhetit from body

2022-10-31 11:10 UTC, Vanderwise commented on css/style.css
> +    display: flex;
Done

2022-10-31 11:10 UTC, Vanderwise commented on css/style.css
> +    height: 40px;
through height and background-color i get the effect that described in spec. when you hover and focus

2022-10-31 11:10 UTC, Vanderwise commented on css/style.css
> +.content-link:focus {
Ok

2022-10-31 11:10 UTC, Vanderwise commented on css/style.css
> +    align-items: center;
Done

2022-10-31 11:10 UTC, Vanderwise commented on css/style.css
> +.search::before {
it dosn't work here.

2022-10-31 11:10 UTC, Vanderwise commented on css/style.css
> +    padding: 0 13px 0 0;
indiceted position for this element and left others as it was. Because it looks the same :)

2022-10-31 11:10 UTC, Vanderwise commented on css/style.css
> +.button-compare::before {
For now I don't see the need to point it out here

2022-10-31 11:10 UTC, Vanderwise commented on css/style.css
> +    display: flex;
Yes, here it works.

2022-10-31 11:10 UTC, Vanderwise commented on css/style.css
> +    padding: 0 0 0 24px;
Ok

2022-10-31 11:10 UTC, Vanderwise commented on css/normalize.css
> +}
i will do it in the next branch

2022-10-31 11:10 UTC, Vanderwise commented on css/style.css
> +}
removed empty lines

2022-10-31 17:28 UTC, ratetenyov commented on device-catalog.html
> +                <a class="nav_link" href=".//index.html"><img src=".//img/logo-black.png" alt="Logo device"></a>
and what?) ok, let it be image, but it can be just text inside of link

2022-10-31 17:30 UTC, ratetenyov commented on device-catalog.html
> +                        <img src=".//img/plus.svg">
this mess is natural for beginners)

2022-10-31 17:34 UTC, ratetenyov commented on device-catalog.html
> +                        <img src=".//img/item-1.jpg" alt="Любительская селфи-палка" width="360" height="380">
just never saw such usage) if it works, than let it be. I would write `img/...`

2022-10-31 17:36 UTC, ratetenyov commented on device-catalog.html
> +                    <!-- <input type="range" min="0" max="9000" step="1000" value="100"> -->
you'll make it look like in design via css

2022-10-31 17:37 UTC, ratetenyov commented on device-catalog.html
> +                <img src=".//img/lable-new.png" alt="new">
stil don't understand what for )))

2022-10-31 17:40 UTC, ratetenyov commented on css/style.css
> +    list-style: none;
to reset this property for ul gobally is ok)

2022-10-31 17:41 UTC, ratetenyov commented on css/style.css
> +    padding: 0 13px 0 0;
if it looks the same doesn't mean it is good

2022-10-31 17:44 UTC, ratetenyov approved these changes

2022-10-31 17:59 UTC, merged